# Generated by Django 6.0.5 on 2026-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('range_name', models.CharField(max_length=100)),
                ('elevation_ft', models.IntegerField()),
                ('is_fourteener', models.BooleanField(default=False)),
                ('prominence_ft', models.IntegerField()),
                ('isolation_mi', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('standard_route', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
